version: '3.8'
services:

  journeys-app:
    image: ${JOURNEYS_IMAGE_REPOSITORY}/journeys-app:${DOCKER_IMAGE_TAG}
    ports:
      - "3000:3000"
    container_name: journeys-app
    working_dir: /app
    command: serve -s build 
    restart: always

  journeys-api:
    image: ${JOURNEYS_IMAGE_REPOSITORY}/journeys-api:${DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
      - "9001:8000"
      - "1099:1099"
    environment:
      CATALINA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.host=localhost"
      JPDA_ADDRESS: "*:8000"
      JPDA_TRANSPORT: dt_socket
      JOURNEYS_DB_HOST: ${JOURNEYS_DB_HOST}
      JOURNEYS_DB_USERNAME: ${JOURNEYS_DB_USERNAME}
      JOURNEYS_DB_PASSWORD: ${JOURNEYS_DB_PASSWORD}
      JOURNEYS_JWT_SECRET: ${JOURNEYS_JWT_SECRET}
      JOURNEYS_ACCESS_TOKEN_NAME: ${JOURNEYS_ACCESS_TOKEN_NAME}
      JOURNEYS_ACCES_TOKEN_DURATION: ${JOURNEYS_ACCES_TOKEN_DURATION}
    container_name: journeys-api
    command : bash -c "/usr/local/tomcat/bin/catalina.sh jpda run"
    volumes:
      - ./images:/usr/local/tomcat/images-poi
    restart: always

networks:
  default:
    name: journeys-web
